paths:
  raw_data: "/vol/data/2025_wristus_wiicontroller_leitner/raw"
  processed_data: "./scratch"

files:
  joystick: "_joystick.npy"
  us_processed: "_US_processed.npy"
  labels: "_labels.npy"

joystick_column: 2  # 1 = x, 2 = y

labels:
  method: "edge_to_derivative"  # "derivative" | "edge_to_peak" | "edge_to_derivative"
  threshold_percent: 10.0  # percentage of max absolute value for threshold (+/-)

display:
  show_raw_trace: true  # show unfiltered raw data as third trace

filters:
  raw:
    lowpass:
      enabled: true
      cutoff: 5  # cutoff frequency in Hz
      fs: 175  # sampling frequency in Hz
      order: 2  # filter order
      ax: 0  # filter along axis
    gaussian:
      enabled: false
      fwhm: 20.0  # full-width at half-maximum for gaussian kernel smoothing
    moving_average:
      enabled: false
      window_size: 50  # number of samples for moving average window
    median:
      enabled: false
      kernel_size: 5  # must be odd number
    savitzky_golay:
      enabled: true
      window_length: 50  # must be odd number
      polyorder: 2  # polynomial order (must be less than window_length)

  derivative:
    lowpass:
      enabled: false
      cutoff: 10  # cutoff frequency in Hz
      fs: 190  # sampling frequency in Hz
      order: 4  # filter order
    gaussian:
      enabled: false
      fwhm: 20.0  # full-width at half-maximum for gaussian kernel smoothing
    moving_average:
      enabled: true
      window_size: 20  # number of samples for moving average window
    median:
      enabled: false
      kernel_size: 49  # must be odd number
    savitzky_golay:
      enabled: false
      window_length: 50  # must be odd number
      polyorder: 2  # polynomial order (must be less than window_length)

include:
  session23_W_010:
    exclude:
      pattern: "odd"
  session14_W_001:
    exclude:
      pattern: "odd"
      double_exclude: [1, 6]
